GET http://localhost:5000/cities?name=k

###

GET http://localhost:5000/cities/802cc0af-0ccc-4609-82be-0705cdc30a4d

###

POST http://localhost:5000/cities
Content-Type: application/json

{
  "city": "Dallas",
  "description": "50+ places",
  "image": "https://images.pexels.com/photos/280193/pexels-photo-280193.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}

###

PUT http://localhost:5000/cities/23ab0bab-a9a2-4f1a-9b62-f45f82ecefca
Content-Type: application/json

{
  "city": "Austin",
  "description": "50+ places",
  "image": "https://images.pexels.com/photos/6312997/pexels-photo-6312997.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}

###

PATCH http://localhost:5000/cities/802cc0af-0ccc-4609-82be-0705cdc30a4d
Content-Type: application/json

{
  "description": "75+ places"
}

###

DELETE http://localhost:5000/cities/23ab0bab-a9a2-4f1a-9b62-f45f82ecefca